#!/bin/bash

# CSS 548; Autumn 2012
# Aaron Hoffer and Daniel Lewis

function testfile()
{
	../lexer <$1 &>test.out
	diff -w $1.out test.out >diff.out
	if [ -s "diff.out" ]
	then
		echo $1 FAILED
		#cat diff.out
	fi
}

# sample program, output provided
testfile array2.p

# sample programs, output generated by our lexer and manually inspected
testfile simplest.p
testfile simplest2.p
testfile if.p
testfile add.p
testfile subscripts.p
testfile case.p
testfile pointer.p
testfile array.p
testfile list.p
testfile fact.p
testfile set.p
testfile nestedprocs.p
#testfile symboltabletest.p
#testfile list2.p
testfile simpleerror.p
#testfile symboltableerror.p
testfile harderror.p
#testfile funcerror.p
testfile arrayerror.p
testfile errors.p

# sample programs, output generated by our lexer and NOT yet manually inspected;
# currently useful only to detect changes
testfile symboltabletest.p
testfile list2.p
testfile symboltableerror.p
testfile funcerror.p

# edge cases
testfile strings.p
testfile comments.p
#testfile untermcomment1.p # needs further consideration
testfile untermcomment2.p
testfile untermstring1.p
testfile untermstring2.p

# cleanup after testfile()
rm -f test.out diff.out
